Update to 1.7

diff --git a/FlashBack/usr/bin/FlashBack b/FlashBack/usr/bin/FlashBack
--- a/FlashBack/usr/bin/FlashBack
+++ b/FlashBack/usr/bin/FlashBack
@@ -24,7 +24,7 @@ DELETEBACKUP=
 DELETESELECT=
 
 BKPVERSION="v2"
-PKGVERSION="1.6"
+PKGVERSION="1.7"
 
 # report(){ # report to dev example function
 # echo "$foo-bar has went wrong"
@@ -39,6 +39,19 @@ killIfIdle(){	#Flashback checks for timeouts and kills itsself if idle for too l
 	fi
 }
 
+prgmNav(){
+	if [[ $LASTINPUT = "QUIT" ]]; then
+    	echo -e "\n\e[0;100m[!]\e[0m \e[104mThanks for using FlashBack!\e[0m"
+		rm -r -f $FLASHBACKDIR/tmp &>/dev/null #clear temp/working files
+		exit 1	#kills child function
+	fi
+	if [[ $LASTINPUT = "BACK" ]]; then
+    	echo -e "\n\e[0;100m[!]\e[0m \e[104mNavigating Back...\e[0m"
+		rm -r -f $FLASHBACKDIR/tmp &>/dev/null #clear temp/working files
+		displayMenu
+	fi
+}
+
 tests() { 
 if [ ! $(id -u) = "0" ] ; then # root check
 	echo -e "\a\n\e[0;100m[*]\e[0m \e[1;31mMust be \e[4;37mroot\e[0m \n\e[1;31m\e[0;100m[*]\e[0m Current User is\e[0m \e[4;37m$USER\e[0m\n"
@@ -46,9 +59,12 @@ exit 1 ; fi
 
 if [ ! -d $FLASHBACKDIR/Backups ] ; then # check for /Library/Flashback/Backups, ask the user to create it if it doesn't exist.
 	echo -e "\n\e[0;100m[*]\e[0m\e[1;31m Directory $FLASHBACKDIR/Backups doesn't exist!\e[0m \n\n\e[1;37mShall it be created?\e[0m"
-	read -rp "	[y/N] " -t 15 response # https://stackoverflow.com/questions/3231804/in-bash-how-to-add-are-you-sure-y-n-to-any-command-or-alias
+	read -rp "	[y/N] " -t 15 RESPONSE # https://stackoverflow.com/questions/3231804/in-bash-how-to-add-are-you-sure-y-n-to-any-command-or-alias
+	LASTINPUT=$RESPONSE
+	prgmNav
+	
 	killIfIdle
-		if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]] # Couldn't remember the expression for this.
+		if [[ "$RESPONSE" =~ ^([yY][eE][sS]|[yY])+$ ]] # Couldn't remember the expression for this.
 			then 	# Do it.
 		 		mkdir -p $FLASHBACKDIR/Backups || exit 1
 			else 	# or Abort.
@@ -72,7 +88,8 @@ one() { # Function that backs-up the current preferences
 	
 	TEMPBACKUPNAME=
 	read -p "`echo -e '\n\e[0;100m[!]\e[0m \e[104mEnter backup name...\e[0m'` > " -t 30 TEMPBACKUPNAME # BACKUPNAME has the date
-	killIfIdle
+	LASTINPUT=$TEMPBACKUPNAME
+	prgmNav && killIfIdle
 	
 	TEMPBACKUPNAME=${TEMPBACKUPNAME//[^a-zA-Z0-9-.]/} # Stop bad inputs
 	if [[ $TEMPBACKUPNAME = "" ]] ; then
@@ -82,11 +99,16 @@ one() { # Function that backs-up the current preferences
 		BACKUPNAME=$TEMPBACKUPNAME; fi
 	set +f
 	BACKUPLOCATION=$FLASHBACKDIR/Backups/$BACKUPNAME
-	mkdir -p $BACKUPLOCATION/{Preferences,SBFolder} || STATUS="mkdir failed"
+	mkdir -p $BACKUPLOCATION/{Preferences,SBFolder,AutoWall} || STATUS="mkdir failed"
 	echo -e "\n\e[0;100m[!]\e[0m \e[104mCopying to $BACKUPLOCATION\e[0m"
 	
 	cp -rf "/var/mobile/Library/Preferences/"!(com.apple*|com.saurik*|ckkeyrolld|nfcd|UITextInputContextIdentifiers|.GlobalPreferences).plist $BACKUPLOCATION/Preferences/ || STATUS="cp failed" #copy all non-apple Plists to Preference folder within backup haha
+	cp -rf "/var/mobile/Library/Preferences/"*(*.jpg|*.png|*.gif) $BACKUPLOCATION/Preferences/ || STATUS="cp failed"	#copy all images to Preference folder within backup
 	cp -rf /var/mobile/Library/SpringBoard/@(*Icon*|*Background*|SB*) $BACKUPLOCATION/SBFolder/ || STATUS="cp failed"		#copy IconState Plist to SBFolder folder within backup
+	if [[ -d /var/mobile/Media/AutoWall/ ]]
+	then
+		cp -rf "/var/mobile/Media/AutoWall/"* "$BACKUPLOCATION/AutoWall/" || STATUS="cp failed"
+	fi
 	touch $BACKUPLOCATION/$BKPVERSION
 	
 	# |||||||||||||||||||||||||||||||||||
@@ -116,7 +138,9 @@ two() { # Restore backups made with function one
 		set -f
 		unset RESET
 		read -p "`echo -e '\n\e[0;100m[!]\e[0m \e[104mSelect Backup\e[0m'` -> " -t 20 SELECTBACKUP
-		killIfIdle
+		LASTINPUT=$SELECTBACKUP
+		prgmNav && killIfIdle
+		
 		SELECTBACKUP=${SELECTBACKUP//[^a-zA-Z0-9-.]/}
 		if [[ $SELECTBACKUP = "" ]] ; then
 			echo -e "\n\e[0;100m[*]\e[0m \e[1;31mBad or no input!\e[0m\n" 
@@ -136,20 +160,29 @@ two() { # Restore backups made with function one
 		
 		echo -e "\n\e[0;100m[!]\e[0m \e[104mMoving current Preferences to $AUTOBACKUPLOCATION\e[0m"
 		
-		mkdir -p $AUTOBACKUPLOCATION/{Preferences,SBFolder} || STATUS="mkdir failed"
+		mkdir -p $AUTOBACKUPLOCATION/{Preferences,SBFolder,AutoWall} || STATUS="mkdir failed"
 		cp "/var/mobile/Library/Preferences/"!(com.apple*|com.saurik*|ckkeyrolld|nfcd|UITextInputContextIdentifiers).plist  $AUTOBACKUPLOCATION/Preferences || STATUS="cp failed"
+		cp -rf "/var/mobile/Library/Preferences/"*(*.jpg|*.png|*.gif) $BACKUPLOCATION/Preferences/ || STATUS="cp failed"
 		cp -r /var/mobile/Library/SpringBoard/@(*Icon*|*Background*|SB*) $AUTOBACKUPLOCATION/SBFolder/ || STATUS="cp failed"
+		if [[ -d /var/mobile/Media/AutoWall/ ]]
+		then
+			cp -rf "/var/mobile/Media/AutoWall/"* "$AUTOBACKUPLOCATION/AutoWall/" || STATUS="cp failed"
+		fi
 		touch $AUTOBACKUPLOCATION/$BKPVERSION
 		
 		echo -e "\n\e[0;100m[!]\e[0m \e[104mCopying Backup to appropriate system directories...\e[0m"
 		
-		cp -r $SELECTLOCATION/Preferences/*.plist /var/mobile/Library/Preferences/ || STATUS="cp failed"
+		cp -r $SELECTLOCATION/Preferences/* /var/mobile/Library/Preferences/ || STATUS="cp failed"
 		cp -r $SELECTLOCATION/SBFolder/* /var/mobile/Library/SpringBoard/ || STATUS="cp failed"
+		if [[ -d $SELECTLOCATION/AutoWall/ ]]
+		then
+			cp -rf $SELECTLOCATION/AutoWall/* /var/mobile/Media/AutoWall/  || STATUS="cp failed"
+		fi
 		
 		echo -e "\n\e[0;100m[*]\e[0m \e[104mRebuilding image cache...\e[0m"
 		
 		uicache || STATUS="uicache failed"
-		recache --no respring || echo -e "\n\e[0;100m[*]\e[0m \e[104mAnemone not installed. Proceeding anyway.\e[0m"
+		recache --no respring &>/dev/null || echo -e "\n\e[0;100m[*]\e[0m \e[104mAnemone not installed. Proceeding anyway.\e[0m"
 		killall cfprefsd #Clear settings caches - thanks to Grant/NewD
 		
 		if [[ ! $STATUS = "" ]] ; then
@@ -183,7 +216,8 @@ three(){ # Function that deletes backups
 				unset RESET
 				set -f
 				read -p "`echo -e '\n\e[0;100m[!]\e[0m \e[104mSelect Backup\e[0m'` -> " -t 30 DELETEBACKUP
-				killIfIdle
+				LASTINPUT=$DELETEBACKUP
+				prgmNav && killIfIdle
 				DELETELOCATION=$FLASHBACKDIR/Backups/$DELETEBACKUP
 				#DELETEBACKUP=${DELETEBACKUP//[^a-zA-Z0-9-.]/}
 			   if [[ $DELETEBACKUP = "" ]]; then
@@ -196,8 +230,9 @@ three(){ # Function that deletes backups
 	
 	DELETECP=
 	echo -e "\n\e[0;100m[!]\e[0m\e[1;31m Are you REALLY sure you want to delete this backup?\e[0m\n \n\e[1;37mType \"FLASHBACK\" exactly the way it is if you're sure!\e[0m\n"
-	read -p "`echo -e ' \e[0;100m---->\e[0m \e[1;31m'` "-t 45 DELETECP
-	killIfIdle
+	read -p "`echo -e ' \e[0;100m---->\e[0m \e[1;31m'` " -t 45 DELETECP
+	LASTINPUT=$DELETECP
+	prgmNav && killIfIdle
 	if [[ $DELETECP = "FLASHBACK" ]]
 	then
 		echo -e "\n\e[0;100m[!]\e[0m \e[104mDeleting $DELETELOCATION\e[0m"
@@ -211,7 +246,8 @@ four(){ # Function that deletes autobackups made in function two
 	DELETEAB=
 	echo -e "\n\e[0;100m[!]\e[0m\e[1;31m Are you REALLY sure you want to delete all AutoBackups?\e[0m\n \n\e[1;37mType \"FLASHBACK\" exactly the way it is if you're sure!\e[0m\n"
 	read -p "`echo -e ' \e[0;100m---->\e[0m \e[1;31m'` " -t 45 DELETEAB
-	killIfIdle
+	LASTINPUT=$DELETEAB
+	prgmNav && killIfIdle
 	if [[ $DELETEAB = "FLASHBACK" ]]
 	then
 		echo -e "\n\e[0;100m[!]\e[0m \e[104mDeleting all autobackups...\e[0m"
@@ -224,9 +260,10 @@ five(){ # I'm not going to painstakingly fix this. You gotta do that yourself. -
 
 	if [ ! -d /var/mobile/Documents/FlashBackDEBs/ ] ; then # check for /Library/Flashback/Backups, ask the user to create it if it doesn't exist.
 		echo -e "\n\e[0;100m[*]\e[0m\e[1;31m Directory /var/mobile/Documents/FlashBackDEBs/ doesn't exist!\e[0m \n\n\e[1;37mShall it be created?\e[0m"
-		read -rp "	[y/N] " -t 15 response # https://stackoverflow.com/questions/3231804/in-bash-how-to-add-are-you-sure-y-n-to-any-command-or-alias
-		killIfIdle
-			if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]] # Couldn't remember the expression for this.
+		read -rp "	[y/N] " -t 15 RESPONSE # https://stackoverflow.com/questions/3231804/in-bash-how-to-add-are-you-sure-y-n-to-any-command-or-alias
+		LASTINPUT=$RESPONSE
+		prgmNav && killIfIdle
+			if [[ "$RESPONSE" =~ ^([yY][eE][sS]|[yY])+$ ]] # Couldn't remember the expression for this.
 				then 	# Do it.
 					mkdir -p /var/mobile/Documents/FlashBackDEBs/ || exit 1
 				else 	# or Abort.
@@ -237,19 +274,23 @@ five(){ # I'm not going to painstakingly fix this. You gotta do that yourself. -
 	for i in $(ls $FLASHBACKDIR/Backups/ || echo "#CRTL-C_to_exit#") ; do # Find and sed are not default commands- can't exclude files.
 		echo -e " \e[100m---->\e[0m  \e[33m$i\e[0m" ; done
 	read -p "`echo -e '\n\e[0;100m[!]\e[0m \e[104mChoose a Backup\e[0m'` > " -t 10 PACKAGEBACKUP
-	killIfIdle
+	LASTINPUT=$PACKAGEBACKUP
+	prgmNav && killIfIdle
 	read -p "`echo -e '\n\e[0;100m[!]\e[0m \e[104mEnter Your UserName\e[0m'` > " -t 20 USERNAME
-	killIfIdle
+	LASTINPUT=$USERNAME
+	prgmNav && killIfIdle
 	read -p "`echo -e '\n\e[0;100m[!]\e[0m \e[104mEnter A Short Description\e[0m'` > " -t 20 USERDESC
-	killIfIdle
+	LASTINPUT=$USERDESC
+	prgmNav && killIfIdle
 	
 	# TODO: MCApollo
 	# Clean the input, wildcard (*) makes it game over.
 	echo -e "\n\e[0;100m~~~~~~~~~~~~~~~~~~~~~~~~~~~\e[0m\n\nWould you like to specify dependancies?\nIf so, it's recommended to use iCleaner Pro to clean up unused preference files before you start.\n\n\e[0;100mAutomatic:\e[0m You select which packages are dependancies, for a streamlined installation.\nThis is highly recommended if you intend to host your setup on a repo, or share with other users.\n\n\e[0;100mManual:\e[0m Dependancies are not set for users, they must install the tweaks themselves.\nThis is recommended if you plan to use this setup personally.\n\n\e[0;100m~~~~~~~~~~~~~~~~~~~~~~~~~~~\e[0m"
-	read -p "`echo -e '\n\e[0;100m[!]\e[0m \e[104mWould you like to proceed in automatic mode? (yes/no)\e[0m'` > " -t 15 autoMode
-	killIfIdle
+	read -p "`echo -e '\n\e[0;100m[!]\e[0m \e[104mWould you like to proceed in automatic mode? (yes/no)\e[0m'` > " -t 15 AUTOMODE
+	LASTINPUT=$AUTOMODE
+	prgmNav && killIfIdle
 	
-	if [[ $autoMode = "yes" ]]
+	if [[ $AUTOMODE = "yes" ]]
 	then
 		read -p "`echo -e '\n\e[0;100m~~~~~~~~~~~~~~~~~~~~~~~~~~~\e[0m\n\n\e[0;100m[!]\e[0m Staring automatic mode. A list of installed packages will appear in a moment.\nUse that list to select which packages are dependancies. \e[104mPress enter to proceed.\e[0m'` > " -t 20
 		killIfIdle
@@ -263,8 +304,9 @@ five(){ # I'm not going to painstakingly fix this. You gotta do that yourself. -
 		# Or better yet, the exit code is 139 if it's a seg fault.
 		# Use the exit code to see if apt seg fault; exit or try again once.
 		
-		read -p "`echo -e '\e[0;100m~~~~~~~~~~~~~~~~~~~~~~~~~~~~\e[0m\n\e[0;100m[!]\e[0m \e[104mPlease copy all desired dependancies from above EXACTLY as they are displayed. Separate them with a comma and a space (, )\e[0m'` > " -t 240 USERSETDEPENDENCIES
-		killIfIdle
+		read -p "`echo -e '\e[0;100m~~~~~~~~~~~~~~~~~~~~~~~~~~~~\e[0m\n\e[0;100m[!]\e[0m \e[104mPlease copy all desired dependancies from above EXACTLY as they are displayed. Separate them with a comma and a space (, )\e[0m'` > " -t 600 USERSETDEPENDENCIES
+		LASTINPUT=$USERSETDEPENDENCIES
+		prgmNav && killIfIdle
 	fi
 	
 	mkdir $FLASHBACKDIR/tmp
@@ -352,11 +394,20 @@ echo -e "\n\e[104m Available Backups: \e[0m \n"
 	
 	if [ -f $UPDATELOCATION/$BKPVERSION ]
 		then
-			echo -e "\n\e[104m [*] Success! \e[0m \n"
-			echo -e "\n\e[104m [*] Your Backup has been updated to work with this version of FlashBack! \e[0m \n"
+			echo -e "\n\e[0;100m[*]\e[0m \e[104mSuccess!\e[0m"
+			echo -e "\n\e[0;100m[*]\e[0m \e[104mYour Backup has been updated to work with this version of FlashBack!\e[0m"
 	fi
 	
 	pause
+}
+
+readme(){
+	echo -e "\n\e[1;31m   When inputting backup\n   names,use plaintext\n   and numbers ONLY!\n   Special characters\n   may result in dangerous\n   side effects!\e[0m\n"
+	echo -e "\n\e[1;31m   PLEASE kill FlashBack\n   Properly! While there\n   are failsafes in place,\n   it is still possible\n   for backgrounding to\n   fall between the cracks!\e[0m\n"
+	echo -e "\n\e[1;31m   To go back to the menu\n   from any screen, just\n   type  'BACK'.\n   To exit FlashBack from\n   any screen, type 'QUIT'\n"
+	echo -e "\n\e[1;31m   Please make sure you\n   watch the video on how\n   to use FlashBack in\n   the Cydia depiction\n   if you're lost!\n"
+	pause
+	
 }
 
 # TODO Idea: MCApollo
@@ -366,15 +417,14 @@ echo -e "\n\e[104m Available Backups: \e[0m \n"
 show_menus() {
 	clear
 	echo -e "   _____________________ \n  |  ___      ___       |\n  | | __|    | _ )      |\n  | | _|     | _ \      |\n  | |_| LASH |___/ACK   |\n  |_____________________|"
-	echo -e "\n\e[1;32m   Please read the FAQ\n   in the Cydia package\n   depiction!" 
-	echo -e "\n\e[1;31m   When inputting backup\n   names,use plaintext\n   and numbers ONLY!\n   Special characters\n   may result in dangerous\n   side effects!\e[0m\n"
-	echo -e "\n\e[1;31m   PLEASE kill FlashBack\n   Properly! While there\n   are failsafes in place,\n   it is still possible\n   for backgrounding to\n   fall between the cracks!\e[0m\n"
+	echo -e "\n\e[1;32m   Please read the FAQ\n   in the Cydia package\n   depiction!\n" 
 	echo -e "\e[0;100m[1.]\e[0m \e[33mBackup Current Preferences\e[0m"
 	echo -e "\e[0;100m[2.]\e[0m \e[33mRestore Backup\e[0m"
 	echo -e "\e[0;100m[3.]\e[0m \e[33mDelete Backups\e[0m"
 	echo -e "\e[0;100m[4.]\e[0m \e[33mDelete AutoBackups\e[0m"
 	echo -e "\e[0;100m[5.]\e[0m \e[33mPackage Backup to DEB\e[0m"
 	echo -e "\e[0;100m[6.]\e[0m \e[33mUpdate Old Backup\e[0m"
+	echo -e "\e[0;100m[R.]\e[0m \e[91mREADME\e[0m"
 	echo -e "\e[0;100m[Q.]\e[0m \e[91mQuit\e[0m"
 }
 
@@ -389,16 +439,23 @@ read_options(){
 		4) four ;;		
 		5) five;;
 		6) six;;
+		R) readme;;
 		Q) exit 0;;
 		*) echo "Invalid Selection!" && sleep 2
 	esac
 }
+displayMenu(){
+	clear
+	shopt -s extglob
+	show_menus
+	echo " "
+	read_options
+}
+
+
 
 tests
 while true
 do
- 	shopt -s extglob
-	show_menus
-	echo " "
-	read_options
+ 	displayMenu
 done
